services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile-caddy
    container_name: caddy
    networks:
      - web
    environment:
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${DOCKER_DATA_DIR}/caddy/data:/data
      - ${DOCKER_DATA_DIR}/caddy/config:/config
    ports:
      - '80:80'
      - '443:443'
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    networks:
      - web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=${QBT_WEBUI_PORT}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA_DIR}/qbittorrent/config:/config
      - ${MEDIA_DIR}:/downloads
    ports:
      - '49174:49174'
      - '49174:49174/udp'
    depends_on:
      - caddy
    restart: always

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: centre
    networks:
      - web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_DATA_DIR}/syncthing/config:/var/syncthing
      - ${DOCKER_DATA_DIR}/syncthing/data:/data
    ports:
      - '22000:22000/udp'
      - '22000:22000/tcp'
      - '21027:21027/udp'
    depends_on:
      - caddy
    restart: always

  linkwarden-db:
    image: postgres:16-alpine
    container_name: linkwarden-db
    networks:
      - linkwarden
    environment:
      - POSTGRES_PASSWORD=${LINKWARDEN_DB_PASSWORD}
    volumes:
      - ${DOCKER_DATA_DIR}/linkwarden-db:/var/lib/postgresql/data

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    networks:
      - web
      - linkwarden
    environment:
      - DATABASE_URL=${LINKWARDEN_DATABASE_URL}
      - NEXTAUTH_URL=${LINKWARDEN_NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${LINKWARDEN_NEXTAUTH_SECRET}
    volumes:
      - ${DOCKER_DATA_DIR}/linkwarden:/data
    depends_on:
      - caddy
      - linkwarden-db

networks:
  web:
    driver: bridge
    name: web
  linkwarden:
    driver: bridge
    name: linkwarden
