services:
  postgres:
    image: postgres:16-alpine
    container_name: dev-postgres
    networks:
      - dev
    enviromment:
      - POSTGRES_USER: ${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB: ${DEV_POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ${DEV_DATA_DIR}/postgres/data:/var/lib/postgresql/data
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    restart: always
